### ISSUE TITLE
Error in sketch

### ISSUE THREAD

**Issue by balbulator** [buxtronix/am43#14]
Help me to understand

Arduino: 1.8.13 (Windows 7), Board:"NodeMCU-32S, 80MHz, 115200"

C:\Users\Sergio\Desktop\am43-master\examples\MQTTBlinds\MQTTBlinds.ino: In member function 'virtual void MyAM43Callbacks::onConnect(AM43Client*)':

MQTTBlinds:111:19: error: 'class PubSubClient' has no member named 'setBufferSize'

       this->mqtt->setBufferSize(512);

                   ^
exit status 1

'class PubSubClient' has no member named 'setBufferSize'

Am I missing something? Thanks in advance

**Comment by buxtronix** [comment]
You need to use the latest version of PubSubClient, 2.8.

**Comment by balbulator** [comment]
Thank you very much, you brought me out of the tracknot!
