### ISSUE TITLE
MQTT overran with Battery messages

### ISSUE THREAD

**Issue by chierichetto** [buxtronix/am43#16]
My AM43 supposedly can't decide between 97 and 100 percent, and is reporting everything back to Home Assistant. 
Maybe add an interval between MQTT publishes to not push at every state change, if something like this happens?
My other one does not behave like this.
![image](https://user-images.githubusercontent.com/18458417/91479910-7ac07280-e8a2-11ea-8935-4c2574ebaf0a.png)

**Comment by buxtronix** [comment]
Yes this has annoyed me also. I've pushed an update to the repo which limits messages to once every 30s.

**Comment by chierichetto** [comment]
Thanks for the quick fix. I also have some problems with the curtains becoming unavailable in HA after a while, but that's a separate issue i haven't been able to get any logs for yet. I'll open a new issue when i have isolated the fault. Maybe a reflash will fix it as well.
