### ISSUE TITLE
set CLOSE \ OPEN not working

### ISSUE THREAD

**Issue by matda59** [buxtronix/am43#20]
When i click on the close or Open blind button it doesn't do anything for this particular blind, all others close and open. I can see that the command is going to the blind, but it doesn't close or open the blind or change the position of the blind - However changing the position of the blind works fine. its not that bad really, except i cannot figure out a way to automate closing this blind via Home assistant though.

![image](https://user-images.githubusercontent.com/27712001/107107748-37bdee80-6887-11eb-92f1-c276a1b8921f.png)

![image](https://user-images.githubusercontent.com/27712001/107107763-5328f980-6887-11eb-98eb-0f90d4741a42.png)

![image](https://user-images.githubusercontent.com/27712001/107107790-7e134d80-6887-11eb-8b62-18ddda9b62f3.png)

**Comment by buxtronix** [comment]
This would imply that the device has not been setup with the 'Blinds Engine' app properly. Please verify that the limits, direction, etc are all as expected.

Otherwise if you can grab a log of the serial port while this is happening, that will help troubleshoot.

**Comment by matda59** [comment]
Outstanding Buxtronix - that worked resetting the blind limits.
