### ISSUE TITLE
AM43 device battery

### ISSUE THREAD

**Issue by Male20** [buxtronix/am43#24]
Hi, 

I am experiencing some serious battery consumption on AM43 (last a week compared to months).  This more likely caused by constant Bluetooth connection and I notice that this is still something on to do list. Is there any progress with this issue.

Thank you.

**Comment by buxtronix** [comment]
The best way to do this is have your automation system disable and enable the bluetooth radio to conserve battery.

The topic is <prefix>/enable which can be "on" or "off". If you write 'off' to it, it will disconnect from all devices. When you write 'on' to it, it will re-enable device connections.

A common way of using this is with automations (such as opening/closing blinds at sunrise/sunset). Have the automation enable the connection, wait a minute or so for the connection to establish, issue the command, then disconnect.
