### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by ccmtozzi** [buxtronix/am43#3]
Just tried the new version and I'm having some compiling issues and hope you can point in me in the right direction! I did load everything as the new README and after configuring I get to "A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header"

I did find a solution in this link [https://randomnerdtutorials.com/solved-failed-to-connect-to-esp32-timed-out-waiting-for-packet-header/](url) and holding boot solved it! Just wanted to have to all since last version didn't work and this kind of fixed that! (wonder why before I wasn't an issue!)

**Comment by buxtronix** [comment]
Ah so the compile worked fine, but the upload failed? Fair enough, a board/hardware issue rather than code.
