### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by frizbeano** [buxtronix/am43#4]
Not a big deal since I did get it to work in the end.

Error Message
**MQTTBlinds:33:24: fatal error: AM43Client.h: No such file or directory
compilation terminated.
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\BlaBla\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.39.0_x86__mdqgnx93n4wtt\libraries\WiFi
exit status 1
AM43Client.h: No such file or directory**

**Steps**

I copied over the **src** files into the **examples** folder and compile

Workaround
Changed 
#include <AM43Client.h>
to
#include  "AM43Client.h"

Which looks into the current **DIR** instead of the lib path I think

**Comment by buxtronix** [comment]
Was this installed in your libraries folder? That would cause this error typically.

**Comment by frizbeano** [comment]
Hi Buxtronix, No this was not installed into my library folder. I just downloaded and opened up the example. This could have been the way I set this up since I'm new to using it

**Comment by buxtronix** [comment]
Thanks, yes it should be installed in your libraries folder.
