### ISSUE TITLE
Add auto-discovery for Home Assistant

### ISSUE THREAD

**Issue by T-REX-XP** [buxtronix/am43#5]
hi. thank you for contributing. Your project very useful. Can you please add auto-discovery function??
here is the example of  implementation: [repo](https://github.com/binsentsu/am43-ctrl)

thanks

**Comment by buxtronix** [comment]
FYI, this should be available shortly, I've been putting some final tweaks to auto discovery.

**Comment by buxtronix** [comment]
Support for this has been pushed to the repo, please give it a try and report back.

**Comment by MrBigleg** [comment]
working for me

**Comment by buxtronix** [comment]
great!

**Comment by jascdk** [comment]
Hi Bus:) BIG THANKS for your hot-damn-cool code! WORKS GREAT - besides the Auto Discovery. I can't get it to work. I have it enabled in the config and HA but nothing shows up. I don't know how to troubleshoot it:(
